# Generated by Django 5.0.7 on 2024-11-06 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_webpage_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('sid', models.IntegerField(primary_key=True, serialize=False)),
                ('sname', models.CharField(max_length=125)),
                ('email', models.EmailField(default='charanbkumar25@gmail.com', max_length=254)),
                ('phone', models.IntegerField()),
            ],
        ),
    ]
